
DEGREES_PER_CIRCLE = 360
DIRECTION_FORWARD = 1
DIRECTION_BACKWARD = 0


DEFAULT_STEPS_PER_REV = 200
DEFAULT_MICROSTEP = 4
DEFAULT_SPEED_RPM = 9.375 


MOTOR1_STEP_PIN = 12
MOTOR1_DIR_PIN = 16
MOTOR1_DIRECTION = DIRECTION_FORWARD

MOTOR2_STEP_PIN = 13
MOTOR2_DIR_PIN = 6
MOTOR2_DIRECTION = DIRECTION_FORWARD
